### ISSUE TITLE
docker stop finish with quit exception....

### ISSUE THREAD

**Issue by mcarbonneaux** [ochinchina/supervisord#225]
when i stop container with supervisord has first process... they quit with exception like that...

```
web_1          | SIGQUIT: quit
web_1          | PC=0x464e31 m=0 sigcode=0
web_1          |
web_1          | goroutine 0 [idle]:
web_1          | runtime.futex(0xc67a08, 0x80, 0x0, 0x0, 0xc000000000, 0x7ffd00000000, 0x43976a, 0x0, 0x7ffd1a8f60c8, 0x40adbf, ...)
web_1          |        /usr/local/go/src/runtime/sys_linux_amd64.s:567 +0x21
web_1          | runtime.futexsleep(0xc67a08, 0x7ffd00000000, 0xffffffffffffffff)
web_1          |        /usr/local/go/src/runtime/os_linux.go:45 +0x46
web_1          | runtime.notesleep(0xc67a08)
web_1          |        /usr/local/go/src/runtime/lock_futex.go:151 +0x9f
web_1          | runtime.stoplockedm()
web_1          |        /usr/local/go/src/runtime/proc.go:1977 +0x88
web_1          | runtime.schedule()
web_1          |        /usr/local/go/src/runtime/proc.go:2460 +0x4a6
web_1          | runtime.park_m(0xc000082c00)
web_1          |        /usr/local/go/src/runtime/proc.go:2696 +0x9d
web_1          | runtime.mcall(0x0)
web_1          |        /usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
web_1          |
web_1          | goroutine 1 [sleep]:
web_1          | time.Sleep(0x2540be400)
web_1          |        /usr/local/go/src/runtime/time.go:188 +0xba
web_1          | main.(*Supervisor).WaitForExit(0xc00009b650)
web_1          |        /go/src/github.com/ochinchina/supervisord/supervisor.go:477 +0x32
web_1          | main.runServer()
web_1          |        /go/src/github.com/ochinchina/supervisord/main.go:131 +0x47
web_1          | main.main()
web_1          |        /go/src/github.com/ochinchina/supervisord/main.go:149 +0x13a
web_1          |
web_1          | goroutine 18 [chan receive]:
web_1          | github.com/ochinchina/supervisord/events.startTickTimer.func1(0xc00009afc0)
web_1          |        /go/src/github.com/ochinchina/supervisord/events/events.go:288 +0x316
web_1          | created by github.com/ochinchina/supervisord/events.startTickTimer
web_1          |        /go/src/github.com/ochinchina/supervisord/events/events.go:284 +0xfd
web_1          |
web_1          | goroutine 19 [sleep]:
web_1          | time.Sleep(0x2540be400)
web_1          |        /usr/local/go/src/runtime/time.go:188 +0xba
web_1          | github.com/ochinchina/filechangemonitor.(*FileChangeMonitor).start.func1(0xc00009b080)
web_1          |        /go/src/github.com/ochinchina/filechangemonitor/file_change_monitor.go:118 +0x14b
web_1          | created by github.com/ochinchina/filechangemonitor.(*FileChangeMonitor).start
web_1          |        /go/src/github.com/ochinchina/filechangemonitor/file_change_monitor.go:104 +0x3f
web_1          |
web_1          | goroutine 20 [select]:
web_1          | github.com/robfig/cron.(*Cron).run(0xc0000b6aa0)
web_1          |        /go/src/github.com/robfig/cron/cron.go:263 +0x541
web_1          | created by github.com/robfig/cron.(*Cron).Start
web_1          |        /go/src/github.com/robfig/cron/cron.go:222 +0xa4
web_1          |
web_1          | goroutine 34 [chan receive]:
web_1          | github.com/ochinchina/go-reaper.sigChildHandler(0xc00011c000)
web_1          |        /go/src/github.com/ochinchina/go-reaper/reaper.go:26 +0xa9
web_1          | created by github.com/ochinchina/go-reaper.reapChildren
web_1          |        /go/src/github.com/ochinchina/go-reaper/reaper.go:45 +0x6a
web_1          |
web_1          | goroutine 33 [chan receive]:
web_1          | github.com/ochinchina/go-reaper.reapChildren(0xffffffffffffffff, 0x0, 0x0)
web_1          |        /go/src/github.com/ochinchina/go-reaper/reaper.go:51 +0x228
web_1          | created by github.com/ochinchina/go-reaper.Start
web_1          |        /go/src/github.com/ochinchina/go-reaper/reaper.go:139 +0x5a
web_1          |
web_1          | goroutine 22 [syscall]:
web_1          | os/signal.signal_recv(0x0)
web_1          |        /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
web_1          | os/signal.loop()
web_1          |        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
web_1          | created by os/signal.Notify.func1
web_1          |        /usr/local/go/src/os/signal/signal.go:127 +0x44
web_1          |
web_1          | goroutine 35 [chan receive]:
web_1          | main.initSignals.func1(0xc0000be300, 0xc00009b650)
web_1          |        /go/src/github.com/ochinchina/supervisord/main.go:38 +0x55
web_1          | created by main.initSignals
web_1          |        /go/src/github.com/ochinchina/supervisord/main.go:37 +0xcb
web_1          |
web_1          | goroutine 36 [syscall]:
web_1          | syscall.Syscall6(0xf7, 0x1, 0xf, 0xc000236f38, 0x1000004, 0x0, 0x0, 0x415676, 0x7fdaa2080f00, 0x100)
web_1          |        /usr/local/go/src/syscall/asm_linux_amd64.s:41 +0x5
web_1          | os.(*Process).blockUntilWaitable(0xc00023e000, 0xc000222100, 0x0, 0x0)
web_1          |        /usr/local/go/src/os/wait_waitid.go:31 +0x98
web_1          | os.(*Process).wait(0xc00023e000, 0xc000112600, 0xc000037800, 0xc0002370c8)
web_1          |        /usr/local/go/src/os/exec_unix.go:22 +0x39
web_1          | os.(*Process).Wait(...)
web_1          |        /usr/local/go/src/os/exec.go:125
web_1          | os/exec.(*Cmd).Wait(0xc00022c000, 0x4d74b5, 0xc0000be060)
web_1          |        /usr/local/go/src/os/exec/exec.go:507 +0x60
web_1          | github.com/ochinchina/supervisord/process.(*Process).waitForExit(0xc00015a000, 0x1)
web_1          |        /go/src/github.com/ochinchina/supervisord/process/process.go:465 +0x57
web_1          | github.com/ochinchina/supervisord/process.(*Process).run(0xc00015a000, 0xc000214000)
web_1          |        /go/src/github.com/ochinchina/supervisord/process/process.go:578 +0x893
web_1          | github.com/ochinchina/supervisord/process.(*Process).Start.func1(0xc000149800, 0x0, 0xc00015a000, 0xc000140464)
web_1          |        /go/src/github.com/ochinchina/supervisord/process/process.go:165 +0xb4
web_1          | created by github.com/ochinchina/supervisord/process.(*Process).Start
web_1          |        /go/src/github.com/ochinchina/supervisord/process/process.go:159 +0x3ad
web_1          |
web_1          | goroutine 37 [syscall]:
web_1          | syscall.Syscall6(0xf7, 0x1, 0xe, 0xc000144f38, 0x1000004, 0x0, 0x0, 0x415676, 0x7fdaa207a400, 0x100)
web_1          |        /usr/local/go/src/syscall/asm_linux_amd64.s:41 +0x5
web_1          | os.(*Process).blockUntilWaitable(0xc000168000, 0x4174fe, 0x7fdaa1f10d40, 0x0)
web_1          |        /usr/local/go/src/os/wait_waitid.go:31 +0x98
web_1          | os.(*Process).wait(0xc000168000, 0xc000112780, 0xc000035000, 0xc0001450c8)
web_1          |        /usr/local/go/src/os/exec_unix.go:22 +0x39
web_1          | os.(*Process).Wait(...)
web_1          |        /usr/local/go/src/os/exec.go:125
web_1          | os/exec.(*Cmd).Wait(0xc00015c000, 0x4d74b5, 0xc0000be060)
web_1          |        /usr/local/go/src/os/exec/exec.go:507 +0x60
web_1          | github.com/ochinchina/supervisord/process.(*Process).waitForExit(0xc00015a0b0, 0x1)
web_1          |        /go/src/github.com/ochinchina/supervisord/process/process.go:465 +0x57
web_1          | github.com/ochinchina/supervisord/process.(*Process).run(0xc00015a0b0, 0xc0001347e0)
web_1          |        /go/src/github.com/ochinchina/supervisord/process/process.go:578 +0x893
web_1          | github.com/ochinchina/supervisord/process.(*Process).Start.func1(0xc000149800, 0x0, 0xc00015a0b0, 0xc000140470)
web_1          |        /go/src/github.com/ochinchina/supervisord/process/process.go:165 +0xb4
web_1          | created by github.com/ochinchina/supervisord/process.(*Process).Start
web_1          |        /go/src/github.com/ochinchina/supervisord/process/process.go:159 +0x3ad
web_1          |
web_1          | goroutine 39 [IO wait]:
web_1          | internal/poll.runtime_pollWait(0x7fdaa1e8fb68, 0x72, 0xffffffffffffffff)
web_1          |        /usr/local/go/src/runtime/netpoll.go:203 +0x55
web_1          | internal/poll.(*pollDesc).wait(0xc00011c3d8, 0x72, 0x8001, 0x8000, 0xffffffffffffffff)
web_1          |        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
web_1          | internal/poll.(*pollDesc).waitRead(...)
web_1          |        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
web_1          | internal/poll.(*FD).Read(0xc00011c3c0, 0xc000280000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
web_1          |        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
web_1          | os.(*File).read(...)
web_1          |        /usr/local/go/src/os/file_unix.go:263
web_1          | os.(*File).Read(0xc000110108, 0xc000280000, 0x8000, 0x8000, 0x3b, 0x0, 0x0)
web_1          |        /usr/local/go/src/os/file.go:116 +0x71
web_1          | io.copyBuffer(0x7fdaa1e8ffc8, 0xc000135320, 0x9744e0, 0xc000110108, 0xc000280000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
web_1          |        /usr/local/go/src/io/io.go:405 +0x122
web_1          | io.Copy(...)
web_1          |        /usr/local/go/src/io/io.go:364
web_1          | os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
web_1          |        /usr/local/go/src/os/exec/exec.go:311 +0x63
web_1          | os/exec.(*Cmd).Start.func1(0xc00015c000, 0xc0001353c0)
web_1          |        /usr/local/go/src/os/exec/exec.go:441 +0x27
web_1          | created by os/exec.(*Cmd).Start
web_1          |        /usr/local/go/src/os/exec/exec.go:440 +0x632
web_1          |
web_1          | goroutine 49 [IO wait]:
web_1          | internal/poll.runtime_pollWait(0x7fdaa1e8f7e8, 0x72, 0xffffffffffffffff)
web_1          |        /usr/local/go/src/runtime/netpoll.go:203 +0x55
web_1          | internal/poll.(*pollDesc).wait(0xc000218138, 0x72, 0x8001, 0x8000, 0xffffffffffffffff)
web_1          |        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
web_1          | internal/poll.(*pollDesc).waitRead(...)
web_1          |        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
web_1          | internal/poll.(*FD).Read(0xc000218120, 0xc000288000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
web_1          |        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
web_1          | os.(*File).read(...)
web_1          |        /usr/local/go/src/os/file_unix.go:263
web_1          | os.(*File).Read(0xc00021c040, 0xc000288000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
web_1          |        /usr/local/go/src/os/file.go:116 +0x71
web_1          | io.copyBuffer(0x7fdaa1e8ffc8, 0xc000214780, 0x9744e0, 0xc00021c040, 0xc000288000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
web_1          |        /usr/local/go/src/io/io.go:405 +0x122
web_1          | io.Copy(...)
web_1          |        /usr/local/go/src/io/io.go:364
web_1          | os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
web_1          |        /usr/local/go/src/os/exec/exec.go:311 +0x63
web_1          | os/exec.(*Cmd).Start.func1(0xc00022c000, 0xc000214bc0)
web_1          |        /usr/local/go/src/os/exec/exec.go:441 +0x27
web_1          | created by os/exec.(*Cmd).Start
web_1          |        /usr/local/go/src/os/exec/exec.go:440 +0x632
web_1          |
web_1          | rax    0xca
web_1          | rbx    0xc678c0
web_1          | rcx    0x464e33
web_1          | rdx    0x0
web_1          | rdi    0xc67a08
web_1          | rsi    0x80
web_1          | rbp    0x7ffd1a8f6090
web_1          | rsp    0x7ffd1a8f6048
web_1          | r8     0x0
web_1          | r9     0x0
web_1          | r10    0x0
web_1          | r11    0x286
web_1          | r12    0xff
web_1          | r13    0x0
web_1          | r14    0x964e3c
web_1          | r15    0x0
web_1          | rip    0x464e31
web_1          | rflags 0x286
web_1          | cs     0x33
web_1          | fs     0x0
web_1          | gs     0x0
mycompose_web_1 exited with code 2
```

**Comment by ochinchina** [comment]
Can you paste your configuration example here?

**Comment by mcarbonneaux** [comment]
i launch supervisord as first process (PID 1) in the container.

The container when i execute "docker stop" on it, receive signal SIG_QUIT to the "PID 1"/supervisord processus and if the process not stop send SIG_KILL after timeout.

i think supervisord not support stoping with SIG_QUIT and throw exception.
