### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by SurferCode** [ochinchina/supervisord#254]
Start a process from web UI provoke a segmentation fault:

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x15 pc=0x7f931e32a8f6]

runtime stack:
runtime.throw(0xb1d871, 0x2a)
        /usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:726 +0x4ac

goroutine 76 [syscall]:
runtime.cgocall(0x93a500, 0xc000516fb8, 0xc00039a180)
        /usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000516f88 sp=0xc000516f50 pc=0x404cbb
os/user._Cfunc_mygetgrnam_r(0xc0003683c0, 0xc000363fe0, 0x7f92cc000b20, 0x400, 0xc00039a180, 0x100000000000000)
        _cgo_gotypes.go:125 +0x4d fp=0xc000516fb8 sp=0xc000516f88 pc=0x80526d
os/user.lookupGroup.func1.1(0xc0003683c0, 0x5, 0x5, 0xc000363fe0, 0xc0000a1570, 0xc00039a180, 0xc000517068)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:146 +0xdf fp=0xc000517008 sp=0xc000516fb8 pc=0x80763f
os/user.lookupGroup.func1(0x44e396)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:146 +0x57 fp=0xc000517050 sp=0xc000517008 pc=0x8076d7
os/user.retryWithBuffer(0xc0000a1570, 0xc000517138, 0x4, 0xc0003a9585)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:247 +0x3e fp=0xc0005170a8 sp=0xc000517050 pc=0x8068de
os/user.lookupGroup(0xc0003a9585, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:141 +0x18e fp=0xc000517190 sp=0xc0005170a8 pc=0x80634e
os/user.LookupGroup(...)
        /usr/local/go/src/os/user/lookup.go:51
github.com/ochinchina/supervisord/process.(*Process).setUser(0xc0000b0160, 0xc000517278, 0xc00049f080)
        /home/xran/supervisord/process/process.go:845 +0x23b fp=0xc000517218 sp=0xc000517190 pc=0x90d2bb
github.com/ochinchina/supervisord/process.(*Process).createProgramCommand(0xc0000b0160, 0xa, 0x11475c0)
        /home/xran/supervisord/process/process.go:414 +0x112 fp=0xc0005173e0 sp=0xc000517218 pc=0x9070d2
github.com/ochinchina/supervisord/process.(*Process).run(0xc0000b0160, 0xc000363480)
        /home/xran/supervisord/process/process.go:558 +0x4e5 fp=0xc000517ce0 sp=0xc0005173e0 pc=0x9086c5
github.com/ochinchina/supervisord/process.(*Process).Start.func1(0xc0000b0160, 0x1, 0xc000098bc0)
        /home/xran/supervisord/process/process.go:162 +0x8e fp=0xc000517fc8 sp=0xc000517ce0 pc=0x90ff4e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000517fd0 sp=0xc000517fc8 pc=0x46cda1
created by github.com/ochinchina/supervisord/process.(*Process).Start

**Comment by SurferCode** [comment]
The same error happen using the command line interface.
 To replicate the bug use the configuration file in attachment.
and in the command line try to start the 4 group of process, the bug occurs during the starting of the third group:
supervisord ctl start gruppo-1:*
supervisord ctl start gruppo-2:*
supervisord ctl start gruppo-3:*    <---- crash
[etc.zip](https://github.com/ochinchina/supervisord/files/6203772/etc.zip)

**Comment by ochinchina** [comment]
can you paste your configuration here?

**Comment by ipsusila** [comment]
It seems that at `bug-3.conf` and `bug-4.conf`, `netcat` is listening to same interface address and port, i.e. `127.0.0.4` port `5666-5669`.  So either of application in `group3` or `group4` will failed because the ports are already used, and these failures causing panic.

**Comment by SurferCode** [comment]
The bug-x.conf file missing the configuration parameter that provoque the panic calling the function **user_lookup**.

In each bug-x.conf you should add for each program the definition of the user and group needed to run the command e.g.:
[program:app-?-?]
user = miu:miu
command=nc -l 127.0.0.4 5669
in this case user=miu and group=miu that both must exist and configure for all program.
 then running the commands:
supervisord ctl start gruppo-1:*
supervisord ctl start gruppo-2:*
supervisord ctl start gruppo-3:* <---- crash
