### ISSUE TITLE
crashed from the http server

### ISSUE THREAD

**Issue by litan1106** [ochinchina/supervisord#261]
```
[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes = 0
pidfile=/var/run/supervisord.pid
user=root
loglevel=error

[supervisorctl]
serverurl=http://localhost:9001
username=%(ENV_SUPERVISOR_USERNAME)s
password=%(ENV_SUPERVISOR_PASSWORD)s

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[inet_http_server]
port=0.0.0.0:9001
username=%(ENV_SUPERVISOR_USERNAME)s
password=%(ENV_SUPERVISOR_PASSWORD)s

[include]
files=/etc/supervisor/conf.d/*.conf
```

```
SIGQUIT: quit
PC=0x46f1c1 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0xe2e830, 0x80, 0x0, 0x0, 0x0, 0x7ffd00000000, 0x40bfaf, 0xc00000001e, 0x7ffdd1a19288, 0x40c33f, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:579 +0x21
runtime.futexsleep(0xe2e830, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os_linux.go:44 +0x46
runtime.notesleep(0xe2e830)
	/usr/local/go/src/runtime/lock_futex.go:159 +0x9f
runtime.mPark()
	/usr/local/go/src/runtime/proc.go:1340 +0x39
runtime.stoplockedm()
	/usr/local/go/src/runtime/proc.go:2451 +0x6e
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:3059 +0x48c
runtime.park_m(0xc000082c00)
	/usr/local/go/src/runtime/proc.go:3274 +0x9d
runtime.mcall(0x3)
	/usr/local/go/src/runtime/asm_amd64.s:327 +0x5b

goroutine 1 [sleep]:
time.Sleep(0x2540be400)
	/usr/local/go/src/runtime/time.go:193 +0xd2
main.(*Supervisor).WaitForExit(0xc00019c6c0)
	/root/gocode/pkg/mod/github.com/ochinchina/supervisord@v0.7.3/supervisor.go:477 +0x32
main.runServer()
	/root/gocode/pkg/mod/github.com/ochinchina/supervisord@v0.7.3/main.go:135 +0x45
main.main()
	/root/gocode/pkg/mod/github.com/ochinchina/supervisord@v0.7.3/main.go:173 +0x225

goroutine 18 [chan receive]:
github.com/ochinchina/supervisord/events.startTickTimer.func1(0xc0000a3020)
	/root/gocode/pkg/mod/github.com/ochinchina/supervisord/events@v0.0.0-20210503132557-74b0760cc12e/events.go:288 +0x325
created by github.com/ochinchina/supervisord/events.startTickTimer
	/root/gocode/pkg/mod/github.com/ochinchina/supervisord/events@v0.0.0-20210503132557-74b0760cc12e/events.go:284 +0xfd

goroutine 33 [sleep]:
time.Sleep(0x2540be400)
	/usr/local/go/src/runtime/time.go:193 +0xd2
github.com/ochinchina/filechangemonitor.(*FileChangeMonitor).start.func1(0xc00019c0c0)
	/root/gocode/pkg/mod/github.com/ochinchina/filechangemonitor@v0.3.1/file_change_monitor.go:118 +0x157
created by github.com/ochinchina/filechangemonitor.(*FileChangeMonitor).start
	/root/gocode/pkg/mod/github.com/ochinchina/filechangemonitor@v0.3.1/file_change_monitor.go:104 +0x3f

goroutine 34 [select]:
github.com/robfig/cron/v3.(*Cron).run(0xc0001ac000)
	/root/gocode/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:263 +0x509
created by github.com/robfig/cron/v3.(*Cron).Start
	/root/gocode/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:222 +0xa5

goroutine 22 [chan receive]:
github.com/ochinchina/go-reaper.sigChildHandler(0xc0000c0d20)
	/root/gocode/pkg/mod/github.com/ochinchina/go-reaper@v0.0.0-20181016012355-6b11389e79fc/reaper.go:26 +0xa9
created by github.com/ochinchina/go-reaper.reapChildren
	/root/gocode/pkg/mod/github.com/ochinchina/go-reaper@v0.0.0-20181016012355-6b11389e79fc/reaper.go:45 +0x6a

goroutine 21 [chan receive]:
github.com/ochinchina/go-reaper.reapChildren(0xffffffffffffffff, 0x0, 0x0)
	/root/gocode/pkg/mod/github.com/ochinchina/go-reaper@v0.0.0-20181016012355-6b11389e79fc/reaper.go:51 +0x239
created by github.com/ochinchina/go-reaper.Start
	/root/gocode/pkg/mod/github.com/ochinchina/go-reaper@v0.0.0-20181016012355-6b11389e79fc/reaper.go:139 +0x5a

goroutine 5 [syscall]:
os/signal.signal_recv(0xafbb60)
	/usr/local/go/src/runtime/sigqueue.go:168 +0xa5
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:151 +0x45

goroutine 24 [chan receive]:
main.initSignals.func1(0xc000180120, 0xc00019c6c0)
	/root/gocode/pkg/mod/github.com/ochinchina/supervisord@v0.7.3/main.go:42 +0x55
created by main.initSignals
	/root/gocode/pkg/mod/github.com/ochinchina/supervisord@v0.7.3/main.go:41 +0xcb

goroutine 25 [IO wait]:
internal/poll.runtime_pollWait(0x7fc524438f18, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000173698, 0x72, 0x0, 0x0, 0xa37ea9)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000173680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:401 +0x212
net.(*netFD).accept(0xc000173680, 0x30, 0x7fc54b0be5b8, 0x30)
	/usr/local/go/src/net/fd_unix.go:172 +0x45
net.(*UnixListener).accept(0xc00027e810, 0xc000093a70, 0x40e238, 0x30)
	/usr/local/go/src/net/unixsock_posix.go:162 +0x32
net.(*UnixListener).Accept(0xc00027e810, 0x9eebe0, 0xc00027e990, 0x989d00, 0xddaae0)
	/usr/local/go/src/net/unixsock.go:260 +0x65
net/http.(*Server).Serve(0xc0002661c0, 0xaff270, 0xc00027e810, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2981 +0x285
net/http.Serve(...)
	/usr/local/go/src/net/http/server.go:2529
main.(*XMLRPC).startHTTPServer(0xc0001861a0, 0xc000024134, 0xa, 0xc000024054, 0xa, 0xa36e1f, 0x4, 0xc0000bc2e8, 0x18, 0xc00019c6c0, ...)
	/root/gocode/pkg/mod/github.com/ochinchina/supervisord@v0.7.3/xmlrpc.go:121 +0xae7
main.(*XMLRPC).StartUnixHTTPServer(0xc0001861a0, 0xc000024134, 0xa, 0xc000024054, 0xa, 0xc0000bc2e8, 0x18, 0xc00019c6c0, 0xc00009fe90)
	/root/gocode/pkg/mod/github.com/ochinchina/supervisord@v0.7.3/xmlrpc.go:84 +0xc5
created by main.(*Supervisor).startHTTPServer
	/root/gocode/pkg/mod/github.com/ochinchina/supervisord@v0.7.3/supervisor.go:539 +0x49a

goroutine 49 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x55, 0xc00021cf38, 0x1000004, 0x0, 0x0, 0x0, 0x1, 0xe765db9800000003)
	/usr/local/go/src/syscall/asm_linux_amd64.s:43 +0x5
os.(*Process).blockUntilWaitable(0xc0002fa9f0, 0x5, 0x0, 0xc000292738)
	/usr/local/go/src/os/wait_waitid.go:32 +0x9e
os.(*Process).wait(0xc0002fa9f0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:22 +0x39
os.(*Process).Wait(...)
	/usr/local/go/src/os/exec.go:129
os/exec.(*Cmd).Wait(0xc0002ce000, 0xc0002be000, 0x200000003)
	/usr/local/go/src/os/exec/exec.go:507 +0x65
github.com/ochinchina/supervisord/process.(*Process).waitForExit(0xc0000e1130, 0x1)
	/root/gocode/pkg/mod/github.com/ochinchina/supervisord/process@v0.0.0-20210503132557-74b0760cc12e/process.go:486 +0x57
github.com/ochinchina/supervisord/process.(*Process).run(0xc0000e1130, 0xc000286048)
	/root/gocode/pkg/mod/github.com/ochinchina/supervisord/process@v0.0.0-20210503132557-74b0760cc12e/process.go:599 +0x8f1
github.com/ochinchina/supervisord/process.(*Process).Start.func1(0xc0000e1130, 0x0, 0x0)
	/root/gocode/pkg/mod/github.com/ochinchina/supervisord/process@v0.0.0-20210503132557-74b0760cc12e/process.go:162 +0x8e
created by github.com/ochinchina/supervisord/process.(*Process).Start
	/root/gocode/pkg/mod/github.com/ochinchina/supervisord/process@v0.0.0-20210503132557-74b0760cc12e/process.go:159 +0x38d

goroutine 50 [IO wait]:
internal/poll.runtime_pollWait(0x7fc524438c60, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0002802b8, 0x72, 0x8001, 0x8000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0002802a0, 0xc0001de000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
os.(*File).read(...)
	/usr/local/go/src/os/file_posix.go:31
os.(*File).Read(0xc000282090, 0xc0001de000, 0x8000, 0x8000, 0x1e, 0x0, 0x0)
	/usr/local/go/src/os/file.go:117 +0x77
io.copyBuffer(0x7fc52420d008, 0xc0002d7e00, 0xaf76c0, 0xc000282090, 0xc0001de000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:423 +0x12c
io.Copy(...)
	/usr/local/go/src/io/io.go:382
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:311 +0x65
os/exec.(*Cmd).Start.func1(0xc0002ce000, 0xc0002e3de0)
	/usr/local/go/src/os/exec/exec.go:441 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:440 +0x630

goroutine 51 [IO wait]:
internal/poll.runtime_pollWait(0x7fc524438a90, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000280378, 0x72, 0x8001, 0x8000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000280360, 0xc00031c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
os.(*File).read(...)
	/usr/local/go/src/os/file_posix.go:31
os.(*File).Read(0xc0002820a8, 0xc00031c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:117 +0x77
io.copyBuffer(0x7fc52420d008, 0xc0002e3d80, 0xaf76c0, 0xc0002820a8, 0xc00031c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:423 +0x12c
io.Copy(...)
	/usr/local/go/src/io/io.go:382
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:311 +0x65
os/exec.(*Cmd).Start.func1(0xc0002ce000, 0xc0002e3e00)
	/usr/local/go/src/os/exec/exec.go:441 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:440 +0x630

rax    0xca
rbx    0xe2e6e0
rcx    0x46f1c3
rdx    0x0
rdi    0xe2e830
rsi    0x80
rbp    0x7ffdd1a19250
rsp    0x7ffdd1a19208
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xc00003ffa4
r13    0x0
r14    0xae84bc
r15    0x0
rip    0x46f1c1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

**Comment by litan1106** [comment]
it's working fine after I removed these 
```
username=%(ENV_SUPERVISOR_USERNAME)s
password=%(ENV_SUPERVISOR_PASSWORD)s
```
